### ISSUE TITLE
Missing configurable service

### ISSUE THREAD

**Issue by dalcorta** [ot4i/ace-iseries#2]
On ACE 11 ConfigurableService was removed from IntegrationAPI jar, how would I replace it ?

**Comment by JoergWende** [comment]
you need to create a policy for ACE11. 
Please see the setup file in the v11 branch: https://github.com/ot4i/ace-iseries/blob/v11/setup.md
Cheers
Joerg

**Comment by dalcorta** [comment]
Thanks, didn't see the md file
